### ISSUE TITLE
Visual Studio .NET WebForm - Framework 4.6 compatibility

### ISSUE THREAD

**Issue by jayaramu** [jacerhea/OneLoginClientDotNet#1]
When I tried to add it via Nuget Package, I got the below error:

Error		Could not install package 'OneLogin.API 1.0.8'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Same error upon trying your 1.0 version too. Please help, as your GitHub page says support for Framework 4.5 or more - https://github.com/jacerhea/OneLoginClientDotNet

**Comment by jacerhea** [comment]
Thanks for finding this.  We recently upgrade the project to use .net standard 2.0, but this may have been too early for some users.  I've downgraded the project to use standard 1.3, which should work for projects on .NET framework 4.6 and up. The new release 1.0.9 should resolve this issue for you.

**Comment by jayaramu** [comment]
Thanks. We have few Legacy VB.NET WebForm apps, will this component work there? Please advise
