### ISSUE TITLE
Incomplete Implementation - Not Extensible

### ISSUE THREAD

**Issue by microalps** [jacerhea/OneLoginClientDotNet#5]
I am attempting to utilize the Apps endpoints but find that it is not implemented. The simplest way to implement would have been to create a OneLoginClient extension class to add the methods, but since GetResource, PutResource etc. are marked private a lot of code copying would be required. 

This issue is to request the scope change of these methods. If such a change is approved, I would be happy to submit a PR.

In the future, I would consider contributing my Apps related methods, but since I'm not using the full functionality set it would require more help from other contributors to be complete.

**Comment by jacerhea** [comment]
I've pushed a nuget package and fix for this.

**Comment by microalps** [comment]
Thanks a lot! I didn't intend to ask to expose the Parse - but all good. My version, for comparison, is at [My Fork](https://github.com/microalps/OneLoginClientDotNet/commit/0ff1135ef79e9f9e01ae1097eaa6db39b0c72bc5). I'll create a new PR this week hopefully with my improvements.
